
[
  {
  "detail" : "(banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243771",
  "notes" : "Return placement type: inline",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "getPlacementType",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "(banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243772",
  "notes" : "Return total screen size in pixels",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "getScreenSize",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "(banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243768",
  "notes" : "Should return available screen size in pixels minus tool/status bars",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "getMaxSize",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "(banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1239188",
  "notes" : "Should return current ad position x,y relative to getMaxSize dimensions",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "getCurrentPosition",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "(banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243767",
  "notes" : "Should return default ad position x,y relative to getMaxSize dimensions",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "getDefaultPosition",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Width (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243796",
  "notes" : "Should set expand width to 288px",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setExpandProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Width Height (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243797",
  "notes" : "Should set expand height / width to width:288/height:292",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setExpandProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Width Height UCC (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243798",
  "notes" : "Should set values width:288,height:292,useCustomClose:true",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setExpandProperties",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "All Params (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243780",
  "notes" : "Should set the following properties: width:288,height:292,useCustomClose:true,isModal:true\nNote: isModal is read only\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setExpandProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "String Vs. Boolean (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243794",
  "notes" : "Set the following properties: width:288,height:292,useCustomClose:'true'\nNote: In our SDK, should translate string 'true' to boolean true.\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setExpandProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "String Vs. Integer (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243795",
  "notes" : "Should set the following properties: width:'288',height:'292',useCustomClose:true\nNote: In our SDK, should fail to change because values are not numbers\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setExpandProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Allow Orientation Change (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243800",
  "notes" : "Should set values: allowOrientationChange:false",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setOrientationProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Force Orientation (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243803",
  "notes" : "Should set value: forceOrientation:'landscape'",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setOrientationProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "All Params (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243801",
  "notes" : "Should set values: allowOrientationChange:false,forceOrientation:'portrait'",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setOrientationProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "String Vs. Boolean (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243805",
  "notes" : "Attempt set values: allowOrientationChange:'false',forceOrientation:'portrait'\nNote: should either fail to set or translate string value into boolean\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setOrientationProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Bad Params (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243802",
  "notes" : "Param 'pineapple' should not be accepted",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setOrientationProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Required Only (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243810",
  "notes" : "Should set values: width:295,height:290,offsetX:7,offsetY:8,customClosePosition:'top-right',allowOffscreen:'true'",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setResizeProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "All Params (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243806",
  "notes" : "Should set values: width:295,height:290,offsetX:7,offsetY:8,customClosePosition:'top-left',allowOffscreen:false\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setResizeProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Omit Some Required (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243809",
  "notes" : "Attempt to set values: width:295,offsetY:8\nNote incomplete values, should not set\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setResizeProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Bad Allow Offscreen (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243807",
  "notes" : "Attempt to set values: width:295,height:290,offsetX:7,offsetY:8,customClosePosition:'top-left',allowOffscreen:'pineapple'\nNote: should not accept bad param \"pineapple\"\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setResizeProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Bad CCP Value (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243808",
  "notes" : "Attempt to set values: width:295,height:290,offsetX:7,offsetY:8,customClosePosition:'pineapple',allowOffscreen:'false'\nNote: should not accept bad param \"pineapple\"\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setResizeProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "String Vs. Boolean (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243811",
  "notes" : "Attempt to set values: width:295,height:290,offsetX:7,offsetY:8,customClosePosition:'top-left',allowOffscreen:'false'\nNote: Our SDK refuses the change to allowOffscreen because of the string 'false'\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setResizeProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "String Vs. Integer (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243812",
  "notes" : "Attempt to set values: width:'295',height:'290',offsetX:'7',offsetY:'8',customClosePosition:'top-left',allowOffscreen:false\nShould fail to set or translate string values to int.\n",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setResizeProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Too big / Too small (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243813",
  "notes" : "Attempt to set values too big or too small for device screen size.\nShould fail to set values.",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "setResizeProperties ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "(banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243773",
  "notes" : "Open url to IAD site",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "open",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "(banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243774",
  "notes" : "Play IAB video",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "playVideo",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Simple (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243779",
  "notes" : "Resize ad as shown in icons with partial screen dimensions",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "resize ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Allow Offscreen (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243775",
  "notes" : "When set to true will allow the ad to resize offscreen, when false ad should resize centered",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "resize ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Custom Close Positions (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243778",
  "notes" : "Should resize with custom close in indicated area",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "resize ",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Simple (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243818",
  "notes" : "should expand add to fullscreen",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Expand",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Get tests (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243815",
  "notes" : "Should expand then buttons will get current expand properties.",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Expand",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Expand Again (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243814",
  "notes" : "Both Expand Again Buttons Should do nothing.",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Expand",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Orientation properties (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243816",
  "notes" : "Should expand.  Buttons will return current orientation properties.",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Expand",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Set before expand (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243817",
  "notes" : "Should expand to full screen size.",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Expand",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Two Part (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243819",
  "notes" : "Expand ad to IAB URL",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Expand",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "Two Part: Bad URL (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243820",
  "notes" : "Should expand the current view due to bad url.\nShould have custom close area in upper right corner.",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Expand",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "addEventListener (banner)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "2097854",
  "notes" : "Event ads/removes multiple events fires on error of bad setResizeProperties({ })",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Events",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "(interstitial)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243823",
  "notes" : "These buttons should all result in nothing",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Bad Methods",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "getTests (interstitial)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243824",
  "notes" : "Get tests in interstitial ad.",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Get Tests",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  },
  {
  "detail" : "call/txt/cal/pic/vid (interstitial)",
  "server" : "https://adsx.greystripe.com/openx/www/delivery/ia.php",
  "bolt.Username" : "username",
  "mid" : "1243825",
  "notes" : "Tests for call, text, calendar, picture, and inline video.",
  "bolt.Server" : "https://tools.greystripe.com/bolt/serveAd.php",
  "name" : "Supports",
  "guid" : "296834ba-e559-11e4-b59c-d04f09e98198",
  "serverType.isCobalt" : true,
  "serverType.isBolt" : false,
  "override.Mid" : true
  }
  ]
